version: 2
jobs:
  build:
    working_directory: ~/onken-web
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build for production
          command: yarn run build
      - save-cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
